using PaymentGateway.Services.Models;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace PaymentGateway.Services.Interfaces
{
    public interface IPaymentService
    {
        /// <summary>
        /// record payment and submit to aquiring bank for processing
        /// </summary>
        /// <param name="requestModel"></param>
        /// <returns></returns>
        public Task<int> SubmitPayment(PaymentRequestModel requestModel);

        /// <summary>
        /// Retrieve payment record via ID
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public Task<PaymentRecordModel> GetPaymentRecord(int id);

        /// <summary>
        /// retrieve payment via the ID generated by the bank
        /// </summary>
        /// <param name="bankPaymentId"></param>
        /// <returns></returns>
        public Task<PaymentRecordModel> GetPaymentRecord(Guid bankPaymentId);
    }
}
